name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: chekout git repo
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
        #source-url: https://sample113355.jfrog.io/artifactory/api/nuget/v3/default-nuget
      # env:
      #   NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    
    # Don't need Test cases to be executed for now
    # - name: Test with dotnet
    #   run: dotnet test ./eShopOnWeb.sln --configuration Release
      
    - name: Create the package
      run: dotnet pack --configuration Release ./eShopOnWeb.sln
      
    # - name: Publish the package to JFROG
    #   run: dotnet nuget push ./eShopOnWeb.sln/bin/Release/*.nupkg
    - uses: jfrog/setup-jfrog-cli@v2
      # env:
      #   JF_ENV_1: ${{ secrets.JF_PASSWORD}}      
    - name: Upload Nuget Packages to JFrog Artifactory NuGet registry
      run: |
           jf --version
           jf c add JFServer --artifactory-url https://sample113355.jfrog.io/artifactory --user ${{ secrets.JF_USER }} --access-token ${{ secrets.JF_ACEESS_TOKEN }} --interactive=false
           echo "Current Working location $(pwd)"
           cd /home/runner/work/eShopOnWeb_JFROG/eShopOnWeb_JFROG/src/Infrastructure/bin/Release/
           jf rt u default-nuget-remote Infrastructure.1.0.0.nupkg  
