name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: chekout git repo
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
        #source-url: https://sample113355.jfrog.io/artifactory/api/nuget/v3/default-nuget
      # env:
      #   NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release
      
    - name: Create the package
      run: dotnet pack --configuration Release ./eShopOnWeb.sln
      
    # - name: Publish the package to JFROG
    #   run: dotnet nuget push ./eShopOnWeb.sln/bin/Release/*.nupkg
    - name: Setup JFrog CLI
    - uses: jfrog/setup-jfrog-cli@v2
      env:
        JF_ARTIFACTORY_SERVER: ${{ secrets.JF_PASSWORD}}      
    - name: Upload Nuget Packages to JFrog Artifactory NuGet registry
      run: |
           jf --version
           jf c add JFArtifactServer --artifactory-url https://sample113355.jfrog.io/artifactory/api/nuget/v3/default-nuget --user ${{ secrets.JF_USER }} --interactive=false
           jf rt u Release/*.nupkg default-nuget/my-nuget


