name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: chekout git repo
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
        #source-url: https://sample113355.jfrog.io/artifactory/api/nuget/v3/default-nuget
      # env:
      #   NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    
    # Don't need Test cases to be executed for now
    # - name: Test with dotnet
    #   run: dotnet test ./eShopOnWeb.sln --configuration Release
      
    - name: Create the package
      run: dotnet pack --configuration Release ./eShopOnWeb.sln
      
    # - name: Publish the package to JFROG
    #   run: dotnet nuget push ./eShopOnWeb.sln/bin/Release/*.nupkg
    - uses: jfrog/setup-jfrog-cli@v2
      env:
        JFROG_CLI_LOG_LEVEL: DEBUG
        JFROG_CLI_TRANSITIVE_DOWNLOAD_EXPERIMENTAL: true

      #   JF_ENV_1: ${{ secrets.JF_PASSWORD}}      
    - name: Setup JFrog Artifactory NuGet registry and upload it to "jf-nuget-repo-nuget" Registry
      run: |
           jf --version
           jf c add JFServer --artifactory-url ${{ secrets.JF_NUGET_ARTIFACTORY_URL }} --user ${{ secrets.JF_USER }} --access-token ${{ secrets.JF_ACEESS_TOKEN }}
           cd /home/runner/work/eShopOnWeb_JFROG/eShopOnWeb_JFROG/src/BlazorShared/bin/Release/net6.0
           echo "Current Working location $(pwd)"
           jf rt u BlazorShared.dll .
           cd /home/runner/work/eShopOnWeb_JFROG/eShopOnWeb_JFROG/src/Infrastructure/bin/Release
           jf rt u Infrastructure.1.0.0.nupkg .

    # - name: Upload Nuget Packages to JFrog Remote Artifactory NuGet registry
    #   run: |
    #        jf c add JFServer1 --artifactory-url https://sample113355.jfrog.io/artifactory/jf-nuget-repo-nuget-remote-cache/ --user ${{ secrets.JF_USER }} --access-token ${{ secrets.JF_ACEESS_TOKEN }}
    #        cd /home/runner/work/eShopOnWeb_JFROG/eShopOnWeb_JFROG/src/Infrastructure/bin/Release
    #        jf rt u Infrastructure.1.0.0.nupkg /

    - name: Download Nuget Packages from JFrog Artifactory NuGet registry
      run: |
           echo "Current Working location $(pwd)"
           ls -ltrs
           jfrog rt download jf-nuget-repo-nuget-local/* .
           jfrog rt download jf-nuget-repo-nuget-local/BlazorShared.dll .